import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Home,Heart,Library,Upload,Plus,Play,Pause,SkipBack,SkipForward,Volume2,Download,MoreHorizontal,Music2,LogIn,LogOut,UserRound,X,ChevronDown,Disc3} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'/api'; const MEDIA=import.meta.env.VITE_MEDIA_URL||'';
const api=async(path,opts={})=>{const token=localStorage.getItem('melodia_token');const headers={...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch(`${API}${path}`,{...opts,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Request failed');return d};
const img=(url)=>url?.startsWith('http')?url:`${MEDIA}${url||'/covers/default.svg'}`;
const DB_NAME='melodia-offline'; const DB_STORE='tracks';
function openOfflineDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(DB_STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveOffline(track,blob){const db=await openOfflineDB();await new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put({id:track._id,track,blob,createdAt:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}
async function getOffline(){const db=await openOfflineDB();return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readonly');const r=tx.objectStore(DB_STORE).getAll();r.onsuccess=()=>{db.close();res(r.result||[])};r.onerror=()=>rej(r.error)})}
async function removeOffline(id){const db=await openOfflineDB();await new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}
function formatTime(s){if(!Number.isFinite(s))return '0:00';const m=Math.floor(s/60),sec=Math.floor(s%60).toString().padStart(2,'0');return `${m}:${sec}`}
function App(){
 const [tracks,setTracks]=useState([]),[view,setView]=useState('home'),[query,setQuery]=useState(''),[genre,setGenre]=useState('All'),[genres,setGenres]=useState([]),[current,setCurrent]=useState(null),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[volume,setVolume]=useState(.75),[user,setUser]=useState(()=>JSON.parse(localStorage.getItem('melodia_user')||'null')),[authOpen,setAuthOpen]=useState(false),[toast,setToast]=useState(''),[liked,setLiked]=useState(new Set()),[playlists,setPlaylists]=useState([]),[showCreate,setShowCreate]=useState(false),[recent,setRecent]=useState([]),[favorites,setFavorites]=useState([]),[offline,setOffline]=useState([]),[uploadOpen,setUploadOpen]=useState(false);
 const audio=useRef(new Audio());
 useEffect(()=>{loadTracks();api('/tracks/genres').then(d=>setGenres(d.genres)).catch(()=>{});},[]);
 useEffect(()=>{const a=audio.current;a.volume=volume;},[volume]);
 useEffect(()=>{const a=audio.current;const tick=()=>setProgress(a.currentTime);const end=()=>{setPlaying(false);setProgress(0);};a.addEventListener('timeupdate',tick);a.addEventListener('ended',end);return()=>{a.removeEventListener('timeupdate',tick);a.removeEventListener('ended',end);};},[]);
 useEffect(()=>{getOffline().then(rows=>setOffline(rows)).catch(()=>{}); if(user){loadPersonal();}},[user]);
 const filtered=useMemo(()=>tracks.filter(t=>genre==='All'||t.genre===genre),[tracks,genre]);
 async function loadTracks(q=query){try{const d=await api(`/tracks${q?`?q=${encodeURIComponent(q)}`:''}`);setTracks(d.tracks)}catch(e){toastMsg(e.message)}}
 async function loadPersonal(){try{const [f,r,p]=await Promise.all([api('/tracks/user/favorites'),api('/tracks/user/recent'),api('/playlists')]);setFavorites(f.tracks);setRecent(r.tracks);setPlaylists(p.playlists);setLiked(new Set(f.tracks.map(x=>x._id)))}catch(e){}}
 function toastMsg(m){setToast(m);setTimeout(()=>setToast(''),3000)}
 async function play(t){try{if(current?._id!==t._id){audio.current.src=img(t.audioUrl);audio.current.load();setCurrent(t);setProgress(0)}await audio.current.play();setPlaying(true);if(user)api(`/tracks/${t._id}/play`,{method:'POST'}).catch(()=>{});}catch(e){toastMsg('This demo track could not be played. Check your internet connection.')}}
 function togglePlay(){if(!current){if(tracks[0])play(tracks[0]);return}if(playing){audio.current.pause();setPlaying(false)}else{audio.current.play().then(()=>setPlaying(true)).catch(()=>{})}}
 function next(delta){if(!current||!tracks.length)return;const i=tracks.findIndex(x=>x._id===current._id);const n=tracks[(i+delta+tracks.length)%tracks.length];play(n)}
 async function favorite(t){if(!user){setAuthOpen(true);return}try{const d=await api(`/tracks/${t._id}/favorite`,{method:'POST'});setLiked(s=>{const n=new Set(s);d.favorite?n.add(t._id):n.delete(t._id);return n});loadPersonal()}catch(e){toastMsg(e.message)}}
 async function createPlaylist(name){try{await api('/playlists',{method:'POST',body:JSON.stringify({name})});setShowCreate(false);loadPersonal();toastMsg('Playlist created')}catch(e){toastMsg(e.message)}}
 async function addToPlaylist(p,t){try{await api(`/playlists/${p._id}/tracks/${t._id}`,{method:'POST'});loadPersonal();toastMsg('Added to playlist')}catch(e){toastMsg(e.message)}}
 async function offlineDownload(t){try{const r=await fetch(img(t.audioUrl));if(!r.ok)throw new Error('Audio unavailable');const b=await r.blob();await saveOffline(t,b);setOffline(await getOffline());toastMsg('Saved for offline listening')}catch(e){toastMsg(e.message)}}
 function logout(){localStorage.removeItem('melodia_token');localStorage.removeItem('melodia_user');setUser(null);setPlaylists([]);setFavorites([]);setRecent([]);toastMsg('Signed out')}
 return <div className="app">
  <aside className="sidebar"><div className="brand"><span className="brandMark"><Music2 size={20}/></span><span>melodia</span></div><nav>
   <button className={view==='home'?'active':''} onClick={()=>setView('home')}><Home size={18}/>Home</button>
   <button className={view==='search'?'active':''} onClick={()=>setView('search')}><Search size={18}/>Search</button>
   <button className={view==='library'?'active':''} onClick={()=>setView('library')}><Library size={18}/>Your Library</button>
  </nav><div className="sideSection"><div className="sideTitle">YOUR COLLECTION</div><button onClick={()=>setView('favorites')}><Heart size={17}/>Liked Songs</button><button onClick={()=>setShowCreate(true)}><Plus size={17}/>New Playlist</button>{playlists.slice(0,5).map(p=><button key={p._id} onClick={()=>setView(`playlist:${p._id}`)}><Disc3 size={16}/>{p.name}</button>)}</div><div className="sidebarBottom"><div className="proCard"><span>Placement project</span><b>Real-world music app</b><small>React · Express · MongoDB</small></div>{user?<button className="logout" onClick={logout}><LogOut size={16}/>Sign out</button>:<button className="loginSide" onClick={()=>setAuthOpen(true)}><LogIn size={16}/>Sign in</button>}</div></aside>
  <main className="main"><header><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(setView('search'),loadTracks())} placeholder="Search songs, artists, albums..."/></div><div className="headerActions">{user?<div className="userChip"><UserRound size={16}/>{user.name}</div>:<button className="signBtn" onClick={()=>setAuthOpen(true)}>Sign in</button>}</div></header>
   {view==='home'&&<HomeView tracks={filtered} genres={genres} genre={genre} setGenre={setGenre} play={play} playing={playing} current={current} favorite={favorite} liked={liked} user={user} recent={recent} onSearch={()=>setView('search')} download={(t)=>downloadTrack(t,toastMsg)} />}
   {view==='search'&&<SearchView query={query} tracks={filtered} play={play} favorite={favorite} liked={liked} onSearch={loadTracks} download={(t)=>downloadTrack(t,toastMsg)}/>} 
   {view==='library'&&<LibraryView user={user} favorites={favorites} recent={recent} playlists={playlists} play={play} favorite={favorite} liked={liked} upload={()=>setUploadOpen(true)} setAuthOpen={setAuthOpen} addToPlaylist={addToPlaylist} download={(t)=>downloadTrack(t,toastMsg)}/>} 
   {view==='offline'&&<OfflineView items={offline} playOffline={(t)=>{const row=offline.find(x=>x.track._id===t._id);if(row){const url=URL.createObjectURL(row.blob);audio.current.src=url;audio.current.load();setCurrent({...t,audioUrl:url,duration:t.duration||0});audio.current.play().then(()=>setPlaying(true)).catch(()=>{});}}} remove={async id=>{await removeOffline(id);setOffline(await getOffline());toastMsg('Removed from offline library')}}/>}
   {view==='favorites'&&<Collection title="Liked Songs" icon={<Heart/>} tracks={favorites} play={play} favorite={favorite} liked={liked} empty="Songs you like will appear here." download={(t)=>downloadTrack(t,toastMsg)}/>} 
   {view.startsWith('playlist:')&&<PlaylistView id={view.split(':')[1]} playlists={playlists} play={play} favorite={favorite} liked={liked} download={(t)=>downloadTrack(t,toastMsg)}/>} 
  </main>
  <Player current={current} playing={playing} progress={progress} volume={volume} setVolume={setVolume} togglePlay={togglePlay} next={()=>next(1)} prev={()=>next(-1)} setProgress={v=>{audio.current.currentTime=v;setProgress(v)}}/>
  {authOpen&&<AuthModal close={()=>setAuthOpen(false)} onUser={u=>{setUser(u);localStorage.setItem('melodia_user',JSON.stringify(u));setAuthOpen(false);toastMsg('Welcome to Melodia')}}/>}
  {uploadOpen&&<UploadModal close={()=>setUploadOpen(false)} onDone={(t)=>{setTracks(x=>[t,...x]);setUploadOpen(false);toastMsg('Track uploaded')}}/>}{showCreate&&<CreatePlaylist close={()=>setShowCreate(false)} create={createPlaylist}/>} {toast&&<div className="toast">{toast}</div>}
 </div>
}
async function downloadTrack(t,toast){if(!t.downloadable){toast('This demo track is stream-only. Download works for tracks you have upload/download rights for.');return}try{const r=await fetch(img(t.audioUrl));const b=await r.blob();await saveOffline(t,b);const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${t.title}.mp3`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Downloaded and saved for offline listening')}catch{toast('Download failed')}}
function HomeView({tracks,genres,genre,setGenre,play,playing,current,favorite,liked,user,recent,onSearch,download}){const hindi=tracks.filter(t=>t.language==='Hindi');const english=tracks.filter(t=>t.language==='English');return <div className="content"><section className="hero"><div><div className="eyebrow">INDIAN + ENGLISH MUSIC</div><h1>Your sound.<br/><span>Your way.</span></h1><p>Discover Indian-inspired and English demo tracks, build playlists, stream online, and save permitted tracks for offline listening.</p><button className="heroBtn" onClick={()=>tracks[0]&&play(tracks[0])}><Play size={17} fill="currentColor"/>Start listening</button></div><div className="heroArt"><div className="orbit one"/><div className="orbit two"/><div className="heroVinyl"><Disc3 size={90}/></div></div></section>{user&&recent.length>0&&<Section title="Recently played"><TrackRow tracks={recent.slice(0,5)} play={play} favorite={favorite} liked={liked} download={download}/></Section>}<section><div className="sectionHead"><h2>Browse by mood</h2><button onClick={onSearch}>View all <ChevronDown size={16}/></button></div><div className="chips"><button className={genre==='All'?'chip active':'chip'} onClick={()=>setGenre('All')}>All</button>{genres.map(g=><button key={g} className={genre===g?'chip active':'chip'} onClick={()=>setGenre(g)}>{g}</button>)}</div></section>{hindi.length>0&&<Section title="🇮🇳 Indian / Hindi collection"><TrackGrid tracks={hindi} play={play} favorite={favorite} liked={liked} download={download}/></Section>}{english.length>0&&<Section title="🇬🇧 English collection"><TrackGrid tracks={english} play={play} favorite={favorite} liked={liked} download={download}/></Section>}</div>}
function SearchView({query,tracks,play,favorite,liked,onSearch,download}){return <div className="content"><div className="pageTitle"><div><span className="eyebrow">DISCOVER</span><h1>Search results</h1><p>{query?`Results for “${query}”`:'Search the Melodia catalog'}</p></div></div><div className="searchLarge"><Search/><input autoFocus defaultValue={query} onKeyDown={e=>e.key==='Enter'&&onSearch(e.currentTarget.value)} placeholder="Try an artist, song or album"/></div><TrackGrid tracks={tracks} play={play} favorite={favorite} liked={liked} download={download}/></div>}
function LibraryView({user,favorites,recent,play,favorite,liked,playlists,setAuthOpen,addToPlaylist,download,upload}){if(!user)return <div className="content emptyPage"><Library size={45}/><h1>Your Library</h1><p>Sign in to save favorites, playlists and listening history.</p><button className="heroBtn" onClick={()=>setAuthOpen(true)}>Sign in</button></div>;return <div className="content"><div className="pageTitle pageFlex"><div><span className="eyebrow">YOUR MUSIC</span><h1>Library</h1><p>Your favorites, history and playlists in one place.</p></div><button className="heroBtn" onClick={upload}><Upload size={17}/>Upload a track</button></div><Section title="Liked Songs"><TrackRow tracks={favorites.slice(0,5)} play={play} favorite={favorite} liked={liked} download={download}/></Section><Section title="Recently played"><TrackRow tracks={recent.slice(0,5)} play={play} favorite={favorite} liked={liked} download={download}/></Section><Section title="Playlists"><div className="playlistGrid">{playlists.map(p=><div className="playlistCard" key={p._id}><img src={img(p.coverUrl)}/><b>{p.name}</b><small>{p.tracks.length} tracks</small></div>)}</div></Section></div>}

function OfflineView({items,playOffline,remove}){return <div className="content"><div className="pageTitle"><span className="eyebrow">NO INTERNET NEEDED</span><h1>Offline library</h1><p>Tracks saved in this browser are available here without a network connection.</p></div>{items.length?<div className="trackList">{items.map(({track})=><div className="row" key={track._id}><button className="numPlay" onClick={()=>playOffline(track)}><Play size={16}/></button><img src={img(track.coverUrl)}/><div className="rowTitle"><b>{track.title}</b><span>{track.artist}</span></div><span className="albumText">{track.album}</span><span className="genreText">{track.genre}</span><button className="iconBtn" onClick={()=>remove(track._id)}><X size={16}/></button><span className="duration">Offline</span></div>)}</div>:<div className="emptyPage small"><Download size={35}/><h2>No offline songs yet</h2><p>Download a permitted track from your library to see it here.</p></div>}</div>}
function UploadModal({close,onDone}){const [file,setFile]=useState(null),[form,setForm]=useState({title:'',artist:'',album:'Uploads',genre:'Other'}),[busy,setBusy]=useState(false),[err,setErr]=useState('');async function submit(e){e.preventDefault();if(!file)return setErr('Choose an audio file');setBusy(true);setErr('');try{const fd=new FormData();fd.append('audio',file);Object.entries(form).forEach(([k,v])=>fd.append(k,v));const d=await api('/upload',{method:'POST',body:fd});onDone(d.track)}catch(x){setErr(x.message)}finally{setBusy(false)}}return <Modal close={close}><div className="auth"><div className="authLogo"><Upload/> Upload track</div><h2>Add your audio</h2><p>Only upload music you own or have permission to distribute.</p><form onSubmit={submit}><input placeholder="Track title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><input placeholder="Artist" value={form.artist} onChange={e=>setForm({...form,artist:e.target.value})}/><input placeholder="Album" value={form.album} onChange={e=>setForm({...form,album:e.target.value})}/><input placeholder="Genre" value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}/><input type="file" accept="audio/*,.mp3,.wav,.ogg,.m4a,.webm" onChange={e=>setFile(e.target.files?.[0]||null)} required/>{err&&<div className="formError">{err}</div>}<button className="heroBtn full" disabled={busy}>{busy?'Uploading...':'Upload track'}</button></form></div></Modal>}

function Collection({title,icon,tracks,play,favorite,liked,empty,download}){return <div className="content"><div className="pageTitle collectionTitle"><div className="collectionIcon">{icon}</div><div><span className="eyebrow">COLLECTION</span><h1>{title}</h1><p>{tracks.length} songs</p></div></div>{tracks.length?<TrackRow tracks={tracks} play={play} favorite={favorite} liked={liked} download={download}/>:<div className="emptyPage small"><Music2 size={35}/><h2>{empty}</h2></div>}</div>}
function PlaylistView({id,playlists,play,favorite,liked,download}){const p=playlists.find(x=>x._id===id);if(!p)return <div className="content"><h1>Playlist not found</h1></div>;return <div className="content"><div className="playlistHero"><img src={img(p.coverUrl)}/><div><span className="eyebrow">PLAYLIST</span><h1>{p.name}</h1><p>{p.description||'Your personal collection'} · {p.tracks.length} tracks</p></div></div><TrackRow tracks={p.tracks} play={play} favorite={favorite} liked={liked} download={download}/></div>}
function Section({title,children}){return <section className="section"><div className="sectionHead"><h2>{title}</h2></div>{children}</section>}
function TrackGrid({tracks,play,favorite,liked,download}){return <div className="trackGrid">{tracks.map(t=><TrackCard key={t._id} t={t} play={play} favorite={favorite} liked={liked} download={download}/>)}{!tracks.length&&<div className="noResults">No tracks found.</div>}</div>}
function TrackCard({t,play,favorite,liked,download}){return <article className="trackCard"><div className="coverWrap"><img src={img(t.coverUrl)}/><button className="coverPlay" onClick={()=>play(t)}><Play size={19} fill="currentColor"/></button></div><div className="trackMeta"><div><b>{t.title}</b><span>{t.artist} · {t.album}</span></div><div className="trackActions"><button onClick={()=>favorite(t)} className={liked.has(t._id)?'liked':''}><Heart size={16} fill={liked.has(t._id)?'currentColor':'none'}/></button>{t.downloadable&&<button onClick={()=>download(t)}><Download size={16}/></button>}</div></div></article>}
function TrackRow({tracks,play,favorite,liked,download}){return <div className="trackList">{tracks.map((t,i)=><div className="row" key={`${t._id}-${i}`}><button className="numPlay" onClick={()=>play(t)}>{i+1}</button><img src={img(t.coverUrl)}/><div className="rowTitle"><b>{t.title}</b><span>{t.artist}</span></div><span className="albumText">{t.album}</span><span className="genreText">{t.genre}</span><button onClick={()=>favorite(t)} className={liked.has(t._id)?'liked iconBtn':'iconBtn'}><Heart size={16} fill={liked.has(t._id)?'currentColor':'none'}/></button>{t.downloadable&&<button className="iconBtn" onClick={()=>download(t)}><Download size={16}/></button>}<span className="duration">{formatTime(t.duration)}</span></div>)}</div>}
function Player({current,playing,progress,volume,setVolume,togglePlay,next,prev,setProgress}){const max=current?.duration||0;return <div className="player"><div className="nowPlaying">{current?<><img src={img(current.coverUrl)}/><div><b>{current.title}</b><span>{current.artist}</span></div></>:<div className="miniEmpty"><Music2 size={18}/><span>Select a song to start</span></div>}</div><div className="controls"><div className="buttons"><button onClick={prev}><SkipBack size={18}/></button><button className="playBtn" onClick={togglePlay}>{playing?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}</button><button onClick={next}><SkipForward size={18}/></button></div><div className="timeline"><span>{formatTime(progress)}</span><input type="range" min="0" max={max||1} value={progress} onChange={e=>setProgress(Number(e.target.value))}/><span>{formatTime(max)}</span></div></div><div className="volume"><Volume2 size={17}/><input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></div></div>}
function AuthModal({close,onUser}){const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setErr('');try{const d=await api(`/auth/${mode==='login'?'login':'register'}`,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('melodia_token',d.token);onUser(d.user)}catch(x){setErr(x.message)}finally{setBusy(false)}}return <Modal close={close}><div className="auth"><div className="authLogo"><Music2/> melodia</div><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p>{mode==='login'?'Continue your listening journey.':'Save favorites and build playlists.'}</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password (6+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/>{err&&<div className="formError">{err}</div>}<button className="heroBtn full" disabled={busy}>{busy?'Please wait...':mode==='login'?'Sign in':'Create account'}</button></form><button className="switchAuth" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New here? Create an account':'Already have an account? Sign in'}</button></div></Modal>}
function CreatePlaylist({close,create}){const [name,setName]=useState('');return <Modal close={close}><div className="auth"><h2>New playlist</h2><p>Give your playlist a name.</p><input autoFocus placeholder="Playlist name" value={name} onChange={e=>setName(e.target.value)}/><button className="heroBtn full" onClick={()=>name.trim()&&create(name.trim())}>Create playlist</button></div></Modal>}
function Modal({children,close}){return <div className="modalBackdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><button className="close" onClick={close}><X/></button>{children}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
